name: Bskypromo Feed Reposter

on:
  schedule:
    - cron: "37 * * * *" # ieder uur op minuut 37 (GitHub cron = UTC)
  workflow_dispatch:

permissions:
  contents: write

jobs:
  run-bot:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          pip install atproto

      - name: Run bot
        env:
          BSKY_USERNAME: ${{ secrets.BSKY_USERNAME }}
          BSKY_PASSWORD: ${{ secrets.BSKY_PASSWORD }}

          FEED_LINK: "https://bsky.app/profile/did:plc:jaka644beit3x4vmmg6yysw7/feed/aaaipcjvdtvu4"
          EXCLUDE_LIST_LINK: "https://bsky.app/profile/did:plc:5si6ivvplllayxrf6h5euwsd/lists/3mfkghzcmt72w"

          MAX_PER_RUN: "100"
          HOURS_BACK: "24"
          CLEANUP_DAYS: "14"
          POST_DELAY_SECONDS: "1.2"

          FEED_MAX_ITEMS: "1000"
          LIST_MEMBER_LIMIT: "500"

          DUP_CHECK_AUTHOR_FEED_LIMIT: "100"
          DUP_CHECK_CACHE: "4000"

          STATE_FILE: "state.json"
        run: python bskypromo_reposter.py

      - name: Commit state
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
          git add state.json
          git commit -m "Update state [auto]" || echo "No changes"
          git push